spring:
  application:
    name: zoetic-server

server:
  port: 8080

swagger:
  enabled: true
  host:
    url: localhost:8080
    path:

---

spring:
  profiles: production

swagger:
  host:
    url: TODO

