apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zoetic-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - zoetic.ozdemirden.com
      secretName: tls-secret
  rules:
    - host: zoetic.ozdemirden.com
      http:
        paths:
          - backend:
              serviceName: zoetic
              servicePort: 80
            path: /
